### ISSUE TITLE
Is this project still being maintained?

### ISSUE THREAD

**Issue by caicancai** [datafusion-contrib/datafusion-java#149]
Hello, thank you very much for your excellent work. I would like to ask if this project is still being maintained.
I hope to integrate Calcite and Datafusion in the future. I have already participated in the work of integrating Arrow in Calcite.

**Comment by caicancai** [comment]
cc @jimexist

**Comment by alamb** [comment]
I do not know of any active maintenance -- if you are willing to help maintain this project, I could add you to the project

👋  (thank you for your past contributions to DataFusion)

**Comment by caicancai** [comment]
> I do not know of any active maintenance -- if you are willing to help maintain this project, I could add you to the project
> 
> 👋 (thank you for your past contributions to DataFusion)

@alamb Thank you for your reply. Thank you very much for your invitation. It is my honor. It is a very challenging and long process to integrate Calcite with Datafusion, but I started to try it because it is what I have always wanted to do. I estimate that I will initiate a discussion in the Calcite community in the first quarter of 2025. Before that, I need to improve Datafusion-java and research its feasibility.

**Comment by jimexist** [comment]
i don't personally use this project so am open to hand over maintenance burden 

i think if this is used in a serious circumstances then people might need to look into the vector api and new way of doing jni (project panama)

**Comment by alamb** [comment]
Thanks @caicancai  and @jimexist  -- I invited @caicancai to be a maintainer of datafusion-java.

Using Calcite and DataFusion is a fascinating idea

Maybe another potential path would be to use substrait as the common plan format

**Comment by caicancai** [comment]
> Thanks @caicancai and @jimexist -- I invited @caicancai to be a maintainer of datafusion-java.
> 
> Using Calcite and DataFusion is a fascinating idea
> 
> Maybe another potential path would be to use substrait as the common plan format

Thank you for your invitation and suggestion. It is a responsibility for me.
I hope you can see the growth of this project by this time next year.

**Comment by caicancai** [comment]
@alamb @jimexist I am not familiar with some parts of this project. Can I ask for your help when I encounter problems?

**Comment by alamb** [comment]
> @alamb @jimexist I am not familiar with some parts of this project. Can I ask for your help when I encounter problems?

I unfortunately don't know anything about the content so I don't think I will be very helpful :(

**Comment by jimexist** [comment]
sure but https://github.com/datafusion-contrib/datafusion-java/discussions might be the best option as it's public
