### ISSUE TITLE
it seems look like no this package in maven repo~

### ISSUE THREAD

**Issue by Fourth-fresh-man** [datafusion-contrib/datafusion-java#29]
![image](https://user-images.githubusercontent.com/41275436/150081516-6031fdac-ffff-4761-888e-ba723d602905.png)

**Comment by Fourth-fresh-man** [comment]
![image](https://user-images.githubusercontent.com/41275436/150081605-fd5d3bac-f86f-49e1-b7d4-3a7750e6cef7.png)

**Comment by Jimexist** [comment]
@Fourth-fresh-man i haven't published to maven central yet. currently the package is published to [GitHub registry][1] but you'll need to include it as a repository first.

for publishing into maven central i'll find some time in next few weeks to do it

[1]: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#installing-a-package

**Comment by Jimexist** [comment]
[here][1] is a link to how to configure GitHub's maven repository

[1]: https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-apache-maven-registry#authenticating-to-github-packages

**Comment by Fourth-fresh-man** [comment]
Thanks! My problem have been resolved.

**Comment by joao-parana** [comment]
Now it is avaiable in https://search.maven.org/artifact/io.github.datafusion-contrib/datafusion-java
