### ISSUE TITLE
Only add maven dependency can't help me to use the api of datafusion

### ISSUE THREAD

**Issue by Fourth-fresh-man** [datafusion-contrib/datafusion-java#30]
Mr. developer, 
  In leveldb or other embedded databases, the CRUD api can often be easily used by simply adding dependencies, but in this project, I need to build the jni lib first, and then manually call the lib before I can use it Its api, is there any plan to build jni into the final dependency of the project in the future?

have a nice day!

**Comment by Jimexist** [comment]
Hi, thanks for the issue.

I intended to do so but it requires setting up cross compilation tool chain for which I don't currently have time.

Anyone who's interested can setup this up. The downside is that the `.jar` file will be bloated with 4+ arch types.

**Comment by Jimexist** [comment]
this is resolved now.
