### ISSUE TITLE
Providing support for streaming dataset results

### ISSUE THREAD

**Issue by NoahFournier** [datafusion-contrib/datafusion-java#67]
Hi there,

I'd like to expose an interface on the java side to access the executeStream method on Datasets, which would let results be streamed as RecordBatches without having to materialise all of the data in memory. Before doing so, I just have a couple of questions:

- Is this library still active? The last commit at the time of writing is from Sep 2022, so I'd like to make sure that any work we contribute would be reviewed/merged
- Is there any appetite for this change to be merged? 
Thanks!

**Comment by grouzen** [comment]
Hello! I'm also interested in implementing datafusion-based module for the Scala library I'm developing right now https://github.com/grouzen/zio-apache-arrow. I'll be happy to help with this issue as well as updating the arrow dependency to the latest version but need to know if the PRs will be merged. Thanks!

**Comment by grouzen** [comment]
Hi @adamreeve! I'm glad to hear that. I'll switch to your fork until we get the original authors' response.

**Comment by adamreeve** [comment]
Hi @Jimexist, you said in #69 that anyone is welcome to create PRs, but given nobody replied to this issue where Noah offereded to contribute this feature it seemed unlikely that a PR would be reviewed. As well as adding this executeStream method, we've made quite a few other changes in our fork including upgrading dependencies, adding tests, exposing configuration options and adding support for listing tables. Would someone be open to reviewing PRs for getting any of these changes merged?

**Comment by Jimexist** [comment]
> given nobody replied to this issue where Noah offereded to contribute this feature it seemed unlikely that a PR would be reviewed.

I am happy to review such PR, just that didn't get notified about this issue somehow

**Comment by adamreeve** [comment]
Okay thanks, as a starting point I've made PR #73 to add some basic unit tests, as I think it's important to have a testing framework in place before adding more features.
