### ISSUE TITLE
Is this repo being maintained? 

### ISSUE THREAD

**Issue by omidb** [datafusion-contrib/datafusion-java#69]
Thanks for providing the bindings. I was wondering if this is being maintained and if there is a process to make sure that it gets updated often.

**Comment by Jimexist** [comment]
> Thanks for providing the bindings. I was wondering if this is being maintained and if there is a process to make sure that it gets updated often.

this is a community contributed project so anyone's welcome to create PRs. "maintained" is a vague term in my opinion.
